export const TOGGLE_SEARCH_OPTION = 'TOGGLE_SEARCH_OPTION';
export const UPDATE_HOSPITAL_DATA = 'UPDATE_HOSPITAL_DATA';
export const UPDATE_RESTAURANT_DATA = 'UPDATE_RESTAURANT_DATA';
export const UPDATE_SALON_DATA = 'UPDATE_SALON_DATA';
export const UPDATE_NECESSITIES_DATA = 'UPDATE_NECESSITIES_DATA';
export const UPDATE_REGION = 'UPDATE_REGION';
export const UPDATE_ADOPTION_LIST = 'UPDATE_ADOPTION_LIST';

export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_AUTHENTICATED = 'UPDATE_AUTHENTICATED';
export const UPDATE_UNAUTHENTICATED = 'UPDATE_UNAUTHENTICATED';
export const UPDATE_CURRENT_ACCOUNT = 'UPDATE_CURRENT_ACCOUNT';
export const REFRESH_SESSION = 'REFRESH_SESSION';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const VERIFY_FAILED = 'VERIFY_FAILED';
